very very long text
fuzzbuck/mindustry.io-plugin pull request #46
Opened 2020-12-02 20:47 UTC by stubbEnable

2020-12-02 20:51 UTC, fuzzbuck requested changes
bruh

2020-12-02 20:51 UTC, fuzzbuck commented on src/main/java/mindustry/plugin/ioMain.java
> -                    player.con.kick("Influx Capacitor failed.");
keep this

2020-12-02 20:51 UTC, fuzzbuck commented on src/main/java/mindustry/plugin/commands/ModeratorCommands.java
> +                    pd.banReason = (args.length >= 3 ? args[2] : "not specified") + "\n" + "[red]You are banned from this server.[][accent]\nReason:[][red] " + pd.banReason + "\n[accent]Until: " + ep
this does not make any sense

2020-12-02 20:51 UTC, fuzzbuck commented on src/main/java/mindustry/plugin/commands/ModeratorCommands.java
> +                    player.con.kick("[red]You are banned from this server.[][accent]\nReason:[][red] " + pd.banReason + "\n[accent]Until: " + epochToString(until) + "\n[accent]Ban ID:[] " + player.uu
please look above and realise that this does not make any sense

2020-12-02 20:56 UTC, fuzzbuck commented on src/main/java/mindustry/plugin/commands/ModeratorCommands.java
> +                    player.con.kick("[red]You are banned from this server.[][accent]\nReason:[][red] " + pd.banReason + "\n[accent]Until: " + epochToString(until) + "\n[accent]Ban ID:[] " + player.uu
this should be player.con.kick(pd.banReason);

2020-12-03 19:05 UTC, fuzzbuck requested changes

2020-12-03 19:05 UTC, fuzzbuck commented on src/main/java/mindustry/plugin/utils/Funcs.java
> +        return Strings.stripColors(string).replaceAll("`", "");
add this to escapeCharacters() instead of here

have some order you people

2020-12-03 19:37 UTC, stubbEnable commented on src/main/java/mindustry/plugin/utils/Funcs.java
> +        return Strings.stripColors(string).replaceAll("`", "");
not needed, removed it

2020-12-03 20:06 UTC, merged