ban ip pog
fuzzbuck/mindustry.io-plugin pull request #47
Opened 2020-12-03 21:24 UTC by pyronie

adds ip ban that hopefully works with tempbans

2020-12-03 23:17 UTC, fuzzbuck requested changes
you also need to update getData() function with lastIP otherwise it won't even show up

2020-12-03 23:17 UTC, fuzzbuck commented on src/main/java/mindustry/plugin/commands/ModeratorCommands.java
> +            PlayerData pd = getJedisData(args[0]);
this does not work like this anymore
use Database.getData() instead

2020-12-03 23:17 UTC, fuzzbuck commented on src/main/java/mindustry/plugin/commands/ModeratorCommands.java
> +        handler.<Context>register("unbanIP", "<IP>", "Unban the specified player by IP", (args, ctx) -> {
change to unbanip (lowercase)

2020-12-03 23:17 UTC, fuzzbuck commented on src/main/java/mindustry/plugin/commands/ModeratorCommands.java
> +                    ctx.sendEmbed(false, ":wrench: unbanIP failed successfully, IP unable to be found");
???

2020-12-03 23:17 UTC, fuzzbuck commented on src/main/java/mindustry/plugin/commands/ModeratorCommands.java
> +        handler.<Context>register("unbanIP", "<IP>", "Unban the specified player by IP", (args, ctx) -> {
(applies to banip as well)

2020-12-03 23:21 UTC, fuzzbuck commented on src/main/java/mindustry/plugin/utils/Database.java
> +            query.setString(12, pd.lastIP);
switch line 130 with line 131

2020-12-03 23:34 UTC, pyronie commented on src/main/java/mindustry/plugin/commands/ModeratorCommands.java
> +                    ctx.sendEmbed(false, ":wrench: unbanIP failed successfully, IP unable to be found");
it succeeded at failing :P

2020-12-03 23:35 UTC, merged

2020-12-04 02:37 UTC, Volas171 commented
um just wanting to leave comment here (ip bans wont work anyways)